run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - deadcode
    - unused
    - structcheck
    - varcheck

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "generated"

skip-dirs:
  - vendor
  - third_party
