// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    external_id, account_status_code, currency, timezone, locale, net_terms,
    dunning_profile_id, tax_identifiers, billing_address, compliance_flags, metadata
) VALUES ($1, 'PENDING_VERIFICATION', $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING external_id, account_id, account_status_code, currency, timezone, locale,
    net_terms, dunning_profile_id, tax_identifiers, billing_address, compliance_flags, metadata
`

type CreateAccountParams struct {
	ExternalID       pgtype.Text `json:"external_id"`
	Currency         string      `json:"currency"`
	Timezone         string      `json:"timezone"`
	Locale           string      `json:"locale"`
	NetTerms         int16       `json:"net_terms"`
	DunningProfileID pgtype.Int8 `json:"dunning_profile_id"`
	TaxIdentifiers   []byte      `json:"tax_identifiers"`
	BillingAddress   []byte      `json:"billing_address"`
	ComplianceFlags  []byte      `json:"compliance_flags"`
	Metadata         []byte      `json:"metadata"`
}

type CreateAccountRow struct {
	ExternalID        pgtype.Text `json:"external_id"`
	AccountID         int64       `json:"account_id"`
	AccountStatusCode string      `json:"account_status_code"`
	Currency          string      `json:"currency"`
	Timezone          string      `json:"timezone"`
	Locale            string      `json:"locale"`
	NetTerms          int16       `json:"net_terms"`
	DunningProfileID  pgtype.Int8 `json:"dunning_profile_id"`
	TaxIdentifiers    []byte      `json:"tax_identifiers"`
	BillingAddress    []byte      `json:"billing_address"`
	ComplianceFlags   []byte      `json:"compliance_flags"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ExternalID,
		arg.Currency,
		arg.Timezone,
		arg.Locale,
		arg.NetTerms,
		arg.DunningProfileID,
		arg.TaxIdentifiers,
		arg.BillingAddress,
		arg.ComplianceFlags,
		arg.Metadata,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ExternalID,
		&i.AccountID,
		&i.AccountStatusCode,
		&i.Currency,
		&i.Timezone,
		&i.Locale,
		&i.NetTerms,
		&i.DunningProfileID,
		&i.TaxIdentifiers,
		&i.BillingAddress,
		&i.ComplianceFlags,
		&i.Metadata,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :exec
INSERT INTO payment_methods (account_id, payment_provider_code, provider_reference, payment_type_code, is_default, payment_status_code)
VALUES ($1, 'chapa', $2, 'mobile_money', TRUE, 'ACTIVE')
`

type CreatePaymentMethodParams struct {
	AccountID         int64  `json:"account_id"`
	ProviderReference string `json:"provider_reference"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) error {
	_, err := q.db.Exec(ctx, createPaymentMethod, arg.AccountID, arg.ProviderReference)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT external_id, account_id, account_status_code, currency, timezone, locale, net_terms,
    dunning_profile_id, tax_identifiers, billing_address, compliance_flags, metadata
FROM accounts WHERE account_id = $1
`

type GetAccountRow struct {
	ExternalID        pgtype.Text `json:"external_id"`
	AccountID         int64       `json:"account_id"`
	AccountStatusCode string      `json:"account_status_code"`
	Currency          string      `json:"currency"`
	Timezone          string      `json:"timezone"`
	Locale            string      `json:"locale"`
	NetTerms          int16       `json:"net_terms"`
	DunningProfileID  pgtype.Int8 `json:"dunning_profile_id"`
	TaxIdentifiers    []byte      `json:"tax_identifiers"`
	BillingAddress    []byte      `json:"billing_address"`
	ComplianceFlags   []byte      `json:"compliance_flags"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) GetAccount(ctx context.Context, accountID int64) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, accountID)
	var i GetAccountRow
	err := row.Scan(
		&i.ExternalID,
		&i.AccountID,
		&i.AccountStatusCode,
		&i.Currency,
		&i.Timezone,
		&i.Locale,
		&i.NetTerms,
		&i.DunningProfileID,
		&i.TaxIdentifiers,
		&i.BillingAddress,
		&i.ComplianceFlags,
		&i.Metadata,
	)
	return i, err
}

const listPaymentMethodReferences = `-- name: ListPaymentMethodReferences :many
SELECT provider_reference FROM payment_methods WHERE account_id = $1 AND payment_status_code = 'ACTIVE' ORDER BY is_default DESC, payment_method_id
`

func (q *Queries) ListPaymentMethodReferences(ctx context.Context, accountID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPaymentMethodReferences, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider_reference string
		if err := rows.Scan(&provider_reference); err != nil {
			return nil, err
		}
		items = append(items, provider_reference)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts SET account_status_code = $2 WHERE account_id = $1
`

type UpdateAccountStatusParams struct {
	AccountID         int64  `json:"account_id"`
	AccountStatusCode string `json:"account_status_code"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.AccountID, arg.AccountStatusCode)
	return err
}
