// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (
    event_type,
    event_version,
    aggregate_type,
    aggregate_id,
    sequence,
    actor,
    causation_id,
    correlation_id,
    payload
) 
SELECT 
    $1, 
    $2, 
    $3, 
    $4, 
    COALESCE(MAX(e.sequence), 0) + 1,
    $5, 
    $6, 
    $7, 
    $8
FROM (SELECT 1) AS dummy
LEFT JOIN event_log e ON e.aggregate_type = $3 AND e.aggregate_id = $4
GROUP BY e.aggregate_type, e.aggregate_id
RETURNING event_id, sequence, occurred_at
`

type AppendEventParams struct {
	EventType     string     `json:"event_type"`
	EventVersion  int32      `json:"event_version"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	Actor         []byte     `json:"actor"`
	CausationID   *uuid.UUID `json:"causation_id"`
	CorrelationID *uuid.UUID `json:"correlation_id"`
	Payload       []byte     `json:"payload"`
}

type AppendEventRow struct {
	EventID    uuid.UUID `json:"event_id"`
	Sequence   int64     `json:"sequence"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (AppendEventRow, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.EventType,
		arg.EventVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.Actor,
		arg.CausationID,
		arg.CorrelationID,
		arg.Payload,
	)
	var i AppendEventRow
	err := row.Scan(&i.EventID, &i.Sequence, &i.OccurredAt)
	return i, err
}

const readStream = `-- name: ReadStream :many
SELECT 
    event_id,
    event_type,
    event_version,
    aggregate_type,
    aggregate_id,
    sequence,
    actor,
    causation_id,
    correlation_id,
    payload,
    occurred_at
FROM event_log
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY sequence ASC
`

type ReadStreamParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
}

type ReadStreamRow struct {
	EventID       uuid.UUID  `json:"event_id"`
	EventType     string     `json:"event_type"`
	EventVersion  int32      `json:"event_version"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	Sequence      int64      `json:"sequence"`
	Actor         []byte     `json:"actor"`
	CausationID   *uuid.UUID `json:"causation_id"`
	CorrelationID *uuid.UUID `json:"correlation_id"`
	Payload       []byte     `json:"payload"`
	OccurredAt    time.Time  `json:"occurred_at"`
}

func (q *Queries) ReadStream(ctx context.Context, arg ReadStreamParams) ([]ReadStreamRow, error) {
	rows, err := q.db.Query(ctx, readStream, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadStreamRow
	for rows.Next() {
		var i ReadStreamRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.EventVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.Sequence,
			&i.Actor,
			&i.CausationID,
			&i.CorrelationID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readStreamFrom = `-- name: ReadStreamFrom :many
SELECT 
    event_id,
    event_type,
    event_version,
    aggregate_type,
    aggregate_id,
    sequence,
    actor,
    causation_id,
    correlation_id,
    payload,
    occurred_at
FROM event_log
WHERE aggregate_type = $1 
  AND aggregate_id = $2 
  AND sequence >= $3
ORDER BY sequence ASC
`

type ReadStreamFromParams struct {
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	Sequence      int64  `json:"sequence"`
}

type ReadStreamFromRow struct {
	EventID       uuid.UUID  `json:"event_id"`
	EventType     string     `json:"event_type"`
	EventVersion  int32      `json:"event_version"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	Sequence      int64      `json:"sequence"`
	Actor         []byte     `json:"actor"`
	CausationID   *uuid.UUID `json:"causation_id"`
	CorrelationID *uuid.UUID `json:"correlation_id"`
	Payload       []byte     `json:"payload"`
	OccurredAt    time.Time  `json:"occurred_at"`
}

func (q *Queries) ReadStreamFrom(ctx context.Context, arg ReadStreamFromParams) ([]ReadStreamFromRow, error) {
	rows, err := q.db.Query(ctx, readStreamFrom, arg.AggregateType, arg.AggregateID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadStreamFromRow
	for rows.Next() {
		var i ReadStreamFromRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.EventVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.Sequence,
			&i.Actor,
			&i.CausationID,
			&i.CorrelationID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
