// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    account_id,
    invoice_status_code,
    currency,
    subtotal_amount,
    tax_amount,
    discount_amount,
    total_amount,
    amount_paid,
    amount_due
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9
)
RETURNING invoice_id
`

type CreateInvoiceParams struct {
	AccountID         int64  `json:"account_id"`
	InvoiceStatusCode string `json:"invoice_status_code"`
	Currency          string `json:"currency"`
	SubtotalAmount    int64  `json:"subtotal_amount"`
	TaxAmount         int64  `json:"tax_amount"`
	DiscountAmount    int64  `json:"discount_amount"`
	TotalAmount       int64  `json:"total_amount"`
	AmountPaid        int64  `json:"amount_paid"`
	AmountDue         int64  `json:"amount_due"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.AccountID,
		arg.InvoiceStatusCode,
		arg.Currency,
		arg.SubtotalAmount,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.AmountPaid,
		arg.AmountDue,
	)
	var invoice_id int64
	err := row.Scan(&invoice_id)
	return invoice_id, err
}

const createInvoiceLineItem = `-- name: CreateInvoiceLineItem :exec
INSERT INTO invoice_line_items (
    invoice_id,
    item_id,
    subscription_id,
    description,
    quantity_value,
    quantity_unit,
    unit_amount,
    total_amount,
    metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
`

type CreateInvoiceLineItemParams struct {
	InvoiceID      int64          `json:"invoice_id"`
	ItemID         int64          `json:"item_id"`
	SubscriptionID pgtype.Int8    `json:"subscription_id"`
	Description    string         `json:"description"`
	QuantityValue  pgtype.Numeric `json:"quantity_value"`
	QuantityUnit   string         `json:"quantity_unit"`
	UnitAmount     int64          `json:"unit_amount"`
	TotalAmount    int64          `json:"total_amount"`
	Metadata       []byte         `json:"metadata"`
}

func (q *Queries) CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) error {
	_, err := q.db.Exec(ctx, createInvoiceLineItem,
		arg.InvoiceID,
		arg.ItemID,
		arg.SubscriptionID,
		arg.Description,
		arg.QuantityValue,
		arg.QuantityUnit,
		arg.UnitAmount,
		arg.TotalAmount,
		arg.Metadata,
	)
	return err
}

const finalizeInvoice = `-- name: FinalizeInvoice :one
UPDATE invoices
SET invoice_status_code = 'OPEN',
    invoice_number = CONCAT('INV-', TO_CHAR(CURRENT_DATE, 'YYYY'), '-', LPAD(nextval('invoice_number_seq')::text, 6, '0')),
    subtotal_amount = $1,
    tax_amount = $2,
    discount_amount = $3,
    total_amount = $4,
    amount_due = $5,
    due_at = $6,
    finalized_at = $7
WHERE invoice_id = $8
  AND invoice_status_code = 'DRAFT'
RETURNING invoice_number
`

type FinalizeInvoiceParams struct {
	SubtotalAmount int64              `json:"subtotal_amount"`
	TaxAmount      int64              `json:"tax_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	TotalAmount    int64              `json:"total_amount"`
	AmountDue      int64              `json:"amount_due"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	FinalizedAt    pgtype.Timestamptz `json:"finalized_at"`
	InvoiceID      int64              `json:"invoice_id"`
}

func (q *Queries) FinalizeInvoice(ctx context.Context, arg FinalizeInvoiceParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, finalizeInvoice,
		arg.SubtotalAmount,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.AmountDue,
		arg.DueAt,
		arg.FinalizedAt,
		arg.InvoiceID,
	)
	var invoice_number pgtype.Text
	err := row.Scan(&invoice_number)
	return invoice_number, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT
    invoice_id,
    account_id,
    invoice_number,
    invoice_status_code,
    currency,
    subtotal_amount,
    tax_amount,
    discount_amount,
    total_amount,
    amount_paid,
    amount_due,
    due_at,
    finalized_at,
    paid_at
FROM invoices
WHERE invoice_id = $1
`

type GetInvoiceRow struct {
	InvoiceID         int64              `json:"invoice_id"`
	AccountID         int64              `json:"account_id"`
	InvoiceNumber     pgtype.Text        `json:"invoice_number"`
	InvoiceStatusCode string             `json:"invoice_status_code"`
	Currency          string             `json:"currency"`
	SubtotalAmount    int64              `json:"subtotal_amount"`
	TaxAmount         int64              `json:"tax_amount"`
	DiscountAmount    int64              `json:"discount_amount"`
	TotalAmount       int64              `json:"total_amount"`
	AmountPaid        int64              `json:"amount_paid"`
	AmountDue         int64              `json:"amount_due"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) GetInvoice(ctx context.Context, invoiceID int64) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, invoiceID)
	var i GetInvoiceRow
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.InvoiceNumber,
		&i.InvoiceStatusCode,
		&i.Currency,
		&i.SubtotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.AmountDue,
		&i.DueAt,
		&i.FinalizedAt,
		&i.PaidAt,
	)
	return i, err
}

const listInvoiceLineItems = `-- name: ListInvoiceLineItems :many
SELECT
    line_item_id,
    invoice_id,
    item_id,
    subscription_id,
    description,
    quantity_value,
    quantity_unit,
    unit_amount,
    total_amount,
    metadata
FROM invoice_line_items
WHERE invoice_id = $1
ORDER BY line_item_id ASC
`

type ListInvoiceLineItemsRow struct {
	LineItemID     int64          `json:"line_item_id"`
	InvoiceID      int64          `json:"invoice_id"`
	ItemID         int64          `json:"item_id"`
	SubscriptionID pgtype.Int8    `json:"subscription_id"`
	Description    string         `json:"description"`
	QuantityValue  pgtype.Numeric `json:"quantity_value"`
	QuantityUnit   string         `json:"quantity_unit"`
	UnitAmount     int64          `json:"unit_amount"`
	TotalAmount    int64          `json:"total_amount"`
	Metadata       []byte         `json:"metadata"`
}

func (q *Queries) ListInvoiceLineItems(ctx context.Context, invoiceID int64) ([]ListInvoiceLineItemsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLineItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoiceLineItemsRow
	for rows.Next() {
		var i ListInvoiceLineItemsRow
		if err := rows.Scan(
			&i.LineItemID,
			&i.InvoiceID,
			&i.ItemID,
			&i.SubscriptionID,
			&i.Description,
			&i.QuantityValue,
			&i.QuantityUnit,
			&i.UnitAmount,
			&i.TotalAmount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByAccount = `-- name: ListInvoicesByAccount :many
SELECT
    invoice_id,
    account_id,
    invoice_number,
    invoice_status_code,
    currency,
    subtotal_amount,
    tax_amount,
    discount_amount,
    total_amount,
    amount_paid,
    amount_due,
    due_at,
    finalized_at,
    paid_at
FROM invoices
WHERE account_id = $1
ORDER BY invoice_id DESC
`

type ListInvoicesByAccountRow struct {
	InvoiceID         int64              `json:"invoice_id"`
	AccountID         int64              `json:"account_id"`
	InvoiceNumber     pgtype.Text        `json:"invoice_number"`
	InvoiceStatusCode string             `json:"invoice_status_code"`
	Currency          string             `json:"currency"`
	SubtotalAmount    int64              `json:"subtotal_amount"`
	TaxAmount         int64              `json:"tax_amount"`
	DiscountAmount    int64              `json:"discount_amount"`
	TotalAmount       int64              `json:"total_amount"`
	AmountPaid        int64              `json:"amount_paid"`
	AmountDue         int64              `json:"amount_due"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) ListInvoicesByAccount(ctx context.Context, accountID int64) ([]ListInvoicesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByAccountRow
	for rows.Next() {
		var i ListInvoicesByAccountRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AccountID,
			&i.InvoiceNumber,
			&i.InvoiceStatusCode,
			&i.Currency,
			&i.SubtotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.AmountDue,
			&i.DueAt,
			&i.FinalizedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :execrows
UPDATE invoices
SET invoice_status_code = 'PAID',
    amount_paid = $1,
    amount_due = $2,
    paid_at = $3
WHERE invoice_id = $4
`

type MarkInvoicePaidParams struct {
	AmountPaid int64              `json:"amount_paid"`
	AmountDue  int64              `json:"amount_due"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	InvoiceID  int64              `json:"invoice_id"`
}

// Transitions -> PAID. Updates amounts and sets paid_at timestamp.
func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaid,
		arg.AmountPaid,
		arg.AmountDue,
		arg.PaidAt,
		arg.InvoiceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentBalances = `-- name: UpdatePaymentBalances :execrows
UPDATE invoices
SET amount_paid = $1,
    amount_due = $2
WHERE invoice_id = $3
`

type UpdatePaymentBalancesParams struct {
	AmountPaid int64 `json:"amount_paid"`
	AmountDue  int64 `json:"amount_due"`
	InvoiceID  int64 `json:"invoice_id"`
}

// Updates balance details (partial payments, dunning adjustments) without touching status code.
func (q *Queries) UpdatePaymentBalances(ctx context.Context, arg UpdatePaymentBalancesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentBalances, arg.AmountPaid, arg.AmountDue, arg.InvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const voidInvoice = `-- name: VoidInvoice :execrows
UPDATE invoices
SET invoice_status_code = 'VOID'
WHERE invoice_id = $1
`

// Transitions -> VOID. Leaves balances intact for historical audit.
func (q *Queries) VoidInvoice(ctx context.Context, invoiceID int64) (int64, error) {
	result, err := q.db.Exec(ctx, voidInvoice, invoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
