// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID         int64       `json:"account_id"`
	ExternalID        pgtype.Text `json:"external_id"`
	AccountStatusCode string      `json:"account_status_code"`
	Currency          string      `json:"currency"`
	Timezone          string      `json:"timezone"`
	Locale            string      `json:"locale"`
	NetTerms          int16       `json:"net_terms"`
	DunningProfileID  pgtype.Int8 `json:"dunning_profile_id"`
	TaxIdentifiers    []byte      `json:"tax_identifiers"`
	BillingAddress    []byte      `json:"billing_address"`
	ComplianceFlags   []byte      `json:"compliance_flags"`
	Metadata          []byte      `json:"metadata"`
	CreatedAt         time.Time   `json:"created_at"`
}

type AccountStatus struct {
	AccountStatusCode string      `json:"account_status_code"`
	Description       pgtype.Text `json:"description"`
	CreatedAt         time.Time   `json:"created_at"`
}

type BillingInterval struct {
	BillingIntervalCode string      `json:"billing_interval_code"`
	Description         pgtype.Text `json:"description"`
	CreatedAt           time.Time   `json:"created_at"`
}

type CreditLedger struct {
	EntryID                  int64              `json:"entry_id"`
	SourcePartyTypeCode      string             `json:"source_party_type_code"`
	SourcePartyID            string             `json:"source_party_id"`
	DestinationPartyTypeCode string             `json:"destination_party_type_code"`
	DestinationPartyID       string             `json:"destination_party_id"`
	LedgerEntryTypeCode      string             `json:"ledger_entry_type_code"`
	Amount                   int64              `json:"amount"`
	ReferenceType            pgtype.Text        `json:"reference_type"`
	ReferenceID              pgtype.Text        `json:"reference_id"`
	Description              pgtype.Text        `json:"description"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                time.Time          `json:"created_at"`
}

type EventLog struct {
	EventID       uuid.UUID  `json:"event_id"`
	EventType     string     `json:"event_type"`
	AggregateType string     `json:"aggregate_type"`
	AggregateID   string     `json:"aggregate_id"`
	Sequence      int64      `json:"sequence"`
	OccurredAt    time.Time  `json:"occurred_at"`
	Actor         []byte     `json:"actor"`
	CausationID   *uuid.UUID `json:"causation_id"`
	CorrelationID *uuid.UUID `json:"correlation_id"`
	Payload       []byte     `json:"payload"`
	EventVersion  int32      `json:"event_version"`
}

type Invoice struct {
	InvoiceID              int64              `json:"invoice_id"`
	AccountID              int64              `json:"account_id"`
	InvoiceNumber          pgtype.Text        `json:"invoice_number"`
	InvoiceStatusCode      string             `json:"invoice_status_code"`
	Currency               string             `json:"currency"`
	SubtotalAmount         int64              `json:"subtotal_amount"`
	TaxAmount              int64              `json:"tax_amount"`
	DiscountAmount         int64              `json:"discount_amount"`
	TotalAmount            int64              `json:"total_amount"`
	AmountPaid             int64              `json:"amount_paid"`
	AmountDue              int64              `json:"amount_due"`
	DueAt                  pgtype.Timestamptz `json:"due_at"`
	FinalizedAt            pgtype.Timestamptz `json:"finalized_at"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	BillingAddressSnapshot []byte             `json:"billing_address_snapshot"`
	IdempotencyKey         pgtype.Text        `json:"idempotency_key"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              time.Time          `json:"created_at"`
}

type InvoiceLineItem struct {
	LineItemID     int64          `json:"line_item_id"`
	InvoiceID      int64          `json:"invoice_id"`
	ItemID         int64          `json:"item_id"`
	SubscriptionID pgtype.Int8    `json:"subscription_id"`
	Description    string         `json:"description"`
	QuantityValue  pgtype.Numeric `json:"quantity_value"`
	QuantityUnit   string         `json:"quantity_unit"`
	UnitAmount     int64          `json:"unit_amount"`
	TotalAmount    int64          `json:"total_amount"`
	Metadata       []byte         `json:"metadata"`
	CreatedAt      time.Time      `json:"created_at"`
}

type InvoiceStatus struct {
	InvoiceStatusCode string      `json:"invoice_status_code"`
	Description       pgtype.Text `json:"description"`
	CreatedAt         time.Time   `json:"created_at"`
}

type ItemType struct {
	ItemTypeCode string      `json:"item_type_code"`
	Description  pgtype.Text `json:"description"`
	CreatedAt    time.Time   `json:"created_at"`
}

type LedgerEntryType struct {
	LedgerEntryTypeCode string      `json:"ledger_entry_type_code"`
	Description         pgtype.Text `json:"description"`
	CreatedAt           time.Time   `json:"created_at"`
}

type LedgerPartyType struct {
	LedgerPartyTypeCode string      `json:"ledger_party_type_code"`
	Description         pgtype.Text `json:"description"`
	CreatedAt           time.Time   `json:"created_at"`
}

type PaymentAttempt struct {
	AttemptID    int64       `json:"attempt_id"`
	InvoiceID    int64       `json:"invoice_id"`
	ProviderCode string      `json:"provider_code"`
	InternalTxID string      `json:"internal_tx_id"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
	AmountMinor  int64       `json:"amount_minor"`
	Currency     string      `json:"currency"`
	Status       string      `json:"status"`
	RawResponse  []byte      `json:"raw_response"`
	RawRequest   []byte      `json:"raw_request"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type PaymentMethod struct {
	PaymentMethodID     int64     `json:"payment_method_id"`
	AccountID           int64     `json:"account_id"`
	PaymentProviderCode string    `json:"payment_provider_code"`
	ProviderReference   string    `json:"provider_reference"`
	PaymentTypeCode     string    `json:"payment_type_code"`
	IsDefault           bool      `json:"is_default"`
	PaymentStatusCode   string    `json:"payment_status_code"`
	Metadata            []byte    `json:"metadata"`
	CreatedAt           time.Time `json:"created_at"`
}

type PaymentProvider struct {
	PaymentProviderCode string      `json:"payment_provider_code"`
	Description         pgtype.Text `json:"description"`
	CreatedAt           time.Time   `json:"created_at"`
}

type PaymentStatus struct {
	PaymentStatusCode string      `json:"payment_status_code"`
	Description       pgtype.Text `json:"description"`
	CreatedAt         time.Time   `json:"created_at"`
}

type PaymentType struct {
	PaymentTypeCode string      `json:"payment_type_code"`
	Description     pgtype.Text `json:"description"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Plan struct {
	PlanID                int64              `json:"plan_id"`
	PlanCode              string             `json:"plan_code"`
	Version               int32              `json:"version"`
	EffectiveFrom         time.Time          `json:"effective_from"`
	EffectiveUntil        pgtype.Timestamptz `json:"effective_until"`
	LegacyPricePolicyCode string             `json:"legacy_price_policy_code"`
	MigrationPath         []byte             `json:"migration_path"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             time.Time          `json:"created_at"`
}

type PlanDuration struct {
	PlanDurationID int64     `json:"plan_duration_id"`
	PlanID         int64     `json:"plan_id"`
	TariffID       int64     `json:"tariff_id"`
	Duration       int64     `json:"duration"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
}

type PlanLegacyPricePolicy struct {
	LegacyPricePolicyCode string      `json:"legacy_price_policy_code"`
	Description           pgtype.Text `json:"description"`
	CreatedAt             time.Time   `json:"created_at"`
}

type PpiWebhook struct {
	WebhookID    string             `json:"webhook_id"`
	ProviderCode string             `json:"provider_code"`
	EventType    string             `json:"event_type"`
	InternalTxID pgtype.Text        `json:"internal_tx_id"`
	ProviderTxID pgtype.Text        `json:"provider_tx_id"`
	Status       string             `json:"status"`
	Payload      []byte             `json:"payload"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	ProcessedAt  time.Time          `json:"processed_at"`
}

type PricingRule struct {
	RuleID      int64     `json:"rule_id"`
	RuleCode    string    `json:"rule_code"`
	IsActive    bool      `json:"is_active"`
	RulePayload []byte    `json:"rule_payload"`
	CreatedAt   time.Time `json:"created_at"`
}

type PurchasableItem struct {
	ItemID       int64       `json:"item_id"`
	ItemCode     string      `json:"item_code"`
	ItemTypeCode string      `json:"item_type_code"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PlanID       pgtype.Int8 `json:"plan_id"`
	IsActive     bool        `json:"is_active"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type PurchasableItemPricingRule struct {
	ItemID    int64     `json:"item_id"`
	RuleID    int64     `json:"rule_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SmActionBinding struct {
	BindingID    uuid.UUID   `json:"binding_id"`
	DefinitionID uuid.UUID   `json:"definition_id"`
	HookType     string      `json:"hook_type"`
	StateName    pgtype.Text `json:"state_name"`
	TransitionID *uuid.UUID  `json:"transition_id"`
	Seq          int32       `json:"seq"`
	ActionName   string      `json:"action_name"`
	ParamsKind   string      `json:"params_kind"`
	Params       []byte      `json:"params"`
	ParamsScript pgtype.Text `json:"params_script"`
	Mode         string      `json:"mode"`
	OnError      string      `json:"on_error"`
}

type SmActionOutbox struct {
	OutboxID   int64              `json:"outbox_id"`
	InstanceID uuid.UUID          `json:"instance_id"`
	HistoryID  pgtype.Int8        `json:"history_id"`
	BindingID  *uuid.UUID         `json:"binding_id"`
	ActionName string             `json:"action_name"`
	Params     []byte             `json:"params"`
	Status     string             `json:"status"`
	Attempts   int32              `json:"attempts"`
	ClaimedAt  pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy  pgtype.Text        `json:"claimed_by"`
	LastError  pgtype.Text        `json:"last_error"`
	CreatedAt  time.Time          `json:"created_at"`
}

type SmDefinition struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	MachineType  string    `json:"machine_type"`
	Version      int32     `json:"version"`
	InitialState string    `json:"initial_state"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type SmGuardBinding struct {
	TransitionID       uuid.UUID   `json:"transition_id"`
	Seq                int32       `json:"seq"`
	ImplementationKind string      `json:"implementation_kind"`
	GuardName          pgtype.Text `json:"guard_name"`
	Script             pgtype.Text `json:"script"`
	Params             []byte      `json:"params"`
}

type SmInstance struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	DefinitionID uuid.UUID `json:"definition_id"`
	MachineType  string    `json:"machine_type"`
	SubjectType  string    `json:"subject_type"`
	SubjectID    string    `json:"subject_id"`
	CurrentState string    `json:"current_state"`
	Context      []byte    `json:"context"`
	Version      int64     `json:"version"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type SmScheduledTransition struct {
	ScheduleID   uuid.UUID          `json:"schedule_id"`
	InstanceID   uuid.UUID          `json:"instance_id"`
	EventName    string             `json:"event_name"`
	EventPayload []byte             `json:"event_payload"`
	FireAt       time.Time          `json:"fire_at"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy    pgtype.Text        `json:"claimed_by"`
	LastError    pgtype.Text        `json:"last_error"`
	CreatedAt    time.Time          `json:"created_at"`
}

type SmState struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	StateName    string    `json:"state_name"`
	IsFinal      bool      `json:"is_final"`
	Metadata     []byte    `json:"metadata"`
}

type SmTransition struct {
	TransitionID  uuid.UUID   `json:"transition_id"`
	DefinitionID  uuid.UUID   `json:"definition_id"`
	FromState     string      `json:"from_state"`
	EventName     string      `json:"event_name"`
	ToState       string      `json:"to_state"`
	Priority      int32       `json:"priority"`
	EmitEventType pgtype.Text `json:"emit_event_type"`
}

type SmTransitionHistory struct {
	HistoryID     int64       `json:"history_id"`
	InstanceID    uuid.UUID   `json:"instance_id"`
	TransitionID  *uuid.UUID  `json:"transition_id"`
	FromState     pgtype.Text `json:"from_state"`
	ToState       string      `json:"to_state"`
	EventName     pgtype.Text `json:"event_name"`
	EventPayload  []byte      `json:"event_payload"`
	ContextBefore []byte      `json:"context_before"`
	ContextAfter  []byte      `json:"context_after"`
	TriggeredBy   pgtype.Text `json:"triggered_by"`
	OccurredAt    time.Time   `json:"occurred_at"`
}

type Subscription struct {
	SubscriptionID         int64              `json:"subscription_id"`
	AccountID              int64              `json:"account_id"`
	PlanID                 int64              `json:"plan_id"`
	PlanVersion            int32              `json:"plan_version"`
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	Quantity               int32              `json:"quantity"`
	CurrentPeriodStartAt   time.Time          `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time          `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time          `json:"billing_cycle_anchor"`
	TrialStartAt           pgtype.Timestamptz `json:"trial_start_at"`
	TrialEndAt             pgtype.Timestamptz `json:"trial_end_at"`
	CancelAtPeriodEnd      bool               `json:"cancel_at_period_end"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	ResumesAt              pgtype.Timestamptz `json:"resumes_at"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              time.Time          `json:"created_at"`
}

type SubscriptionStatus struct {
	SubscriptionStatusCode string      `json:"subscription_status_code"`
	Description            pgtype.Text `json:"description"`
	CreatedAt              time.Time   `json:"created_at"`
}

type Tariff struct {
	TariffID       int64       `json:"tariff_id"`
	TariffCode     string      `json:"tariff_code"`
	Version        int32       `json:"version"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type TariffType struct {
	TariffTypeCode string      `json:"tariff_type_code"`
	Description    pgtype.Text `json:"description"`
	CreatedAt      time.Time   `json:"created_at"`
}
