// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID         int64              `json:"account_id"`
	ExternalID        pgtype.Text        `json:"external_id"`
	AccountStatusCode string             `json:"account_status_code"`
	Currency          string             `json:"currency"`
	Timezone          string             `json:"timezone"`
	Locale            string             `json:"locale"`
	NetTerms          int16              `json:"net_terms"`
	DunningProfileID  pgtype.Int8        `json:"dunning_profile_id"`
	TaxIdentifiers    []byte             `json:"tax_identifiers"`
	BillingAddress    []byte             `json:"billing_address"`
	ComplianceFlags   []byte             `json:"compliance_flags"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AccountStatus struct {
	AccountStatusCode string             `json:"account_status_code"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type BillingInterval struct {
	BillingIntervalCode string             `json:"billing_interval_code"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CreditLedger struct {
	EntryID                  int64              `json:"entry_id"`
	SourcePartyTypeCode      string             `json:"source_party_type_code"`
	SourcePartyID            string             `json:"source_party_id"`
	DestinationPartyTypeCode string             `json:"destination_party_type_code"`
	DestinationPartyID       string             `json:"destination_party_id"`
	LedgerEntryTypeCode      string             `json:"ledger_entry_type_code"`
	Amount                   int64              `json:"amount"`
	ReferenceType            pgtype.Text        `json:"reference_type"`
	ReferenceID              pgtype.Text        `json:"reference_id"`
	Description              pgtype.Text        `json:"description"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type EventLog struct {
	EventID       pgtype.UUID        `json:"event_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	Sequence      int64              `json:"sequence"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Actor         []byte             `json:"actor"`
	CausationID   pgtype.UUID        `json:"causation_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Payload       []byte             `json:"payload"`
}

type Invoice struct {
	InvoiceID              int64              `json:"invoice_id"`
	AccountID              int64              `json:"account_id"`
	InvoiceNumber          pgtype.Text        `json:"invoice_number"`
	InvoiceStatusCode      string             `json:"invoice_status_code"`
	Currency               string             `json:"currency"`
	SubtotalAmount         int64              `json:"subtotal_amount"`
	TaxAmount              int64              `json:"tax_amount"`
	DiscountAmount         int64              `json:"discount_amount"`
	TotalAmount            int64              `json:"total_amount"`
	AmountPaid             int64              `json:"amount_paid"`
	AmountDue              int64              `json:"amount_due"`
	DueAt                  pgtype.Timestamptz `json:"due_at"`
	FinalizedAt            pgtype.Timestamptz `json:"finalized_at"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	BillingAddressSnapshot []byte             `json:"billing_address_snapshot"`
	IdempotencyKey         pgtype.Text        `json:"idempotency_key"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Version                int64              `json:"version"`
}

type InvoiceLineItem struct {
	LineItemID     int64              `json:"line_item_id"`
	InvoiceID      int64              `json:"invoice_id"`
	ItemID         int64              `json:"item_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	Description    string             `json:"description"`
	QuantityValue  pgtype.Numeric     `json:"quantity_value"`
	QuantityUnit   string             `json:"quantity_unit"`
	UnitAmount     int64              `json:"unit_amount"`
	TotalAmount    int64              `json:"total_amount"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InvoiceStatus struct {
	InvoiceStatusCode string             `json:"invoice_status_code"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ItemType struct {
	ItemTypeCode string             `json:"item_type_code"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntryType struct {
	LedgerEntryTypeCode string             `json:"ledger_entry_type_code"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type LedgerPartyType struct {
	LedgerPartyTypeCode string             `json:"ledger_party_type_code"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type PaymentMethod struct {
	PaymentMethodID     int64              `json:"payment_method_id"`
	AccountID           int64              `json:"account_id"`
	PaymentProviderCode string             `json:"payment_provider_code"`
	ProviderReference   string             `json:"provider_reference"`
	PaymentTypeCode     string             `json:"payment_type_code"`
	IsDefault           bool               `json:"is_default"`
	PaymentStatusCode   string             `json:"payment_status_code"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type PaymentProvider struct {
	PaymentProviderCode string             `json:"payment_provider_code"`
	Description         pgtype.Text        `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type PaymentStatus struct {
	PaymentStatusCode string             `json:"payment_status_code"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PaymentType struct {
	PaymentTypeCode string             `json:"payment_type_code"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	PlanID                int64              `json:"plan_id"`
	PlanCode              string             `json:"plan_code"`
	Version               int32              `json:"version"`
	TariffID              int64              `json:"tariff_id"`
	EffectiveFrom         pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil        pgtype.Timestamptz `json:"effective_until"`
	LegacyPricePolicyCode string             `json:"legacy_price_policy_code"`
	MigrationPath         []byte             `json:"migration_path"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PlanLegacyPricePolicy struct {
	LegacyPricePolicyCode string             `json:"legacy_price_policy_code"`
	Description           pgtype.Text        `json:"description"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type PricingRule struct {
	RuleID      int64              `json:"rule_id"`
	RuleCode    string             `json:"rule_code"`
	IsActive    bool               `json:"is_active"`
	RulePayload []byte             `json:"rule_payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PurchasableItem struct {
	ItemID       int64              `json:"item_id"`
	ItemCode     string             `json:"item_code"`
	ItemTypeCode string             `json:"item_type_code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	PlanID       pgtype.Int8        `json:"plan_id"`
	IsActive     bool               `json:"is_active"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PurchasableItemPricingRule struct {
	ItemID    int64              `json:"item_id"`
	RuleID    int64              `json:"rule_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	SubscriptionID         int64              `json:"subscription_id"`
	AccountID              int64              `json:"account_id"`
	PlanID                 int64              `json:"plan_id"`
	PlanVersion            int32              `json:"plan_version"`
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	Quantity               int32              `json:"quantity"`
	CurrentPeriodStartAt   pgtype.Timestamptz `json:"current_period_start_at"`
	CurrentPeriodEndAt     pgtype.Timestamptz `json:"current_period_end_at"`
	BillingCycleAnchor     pgtype.Timestamptz `json:"billing_cycle_anchor"`
	TrialStartAt           pgtype.Timestamptz `json:"trial_start_at"`
	TrialEndAt             pgtype.Timestamptz `json:"trial_end_at"`
	CancelAtPeriodEnd      bool               `json:"cancel_at_period_end"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	ResumesAt              pgtype.Timestamptz `json:"resumes_at"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type SubscriptionStatus struct {
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	Description            pgtype.Text        `json:"description"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type Tariff struct {
	TariffID            int64              `json:"tariff_id"`
	TariffCode          string             `json:"tariff_code"`
	Version             int32              `json:"version"`
	Name                string             `json:"name"`
	Description         pgtype.Text        `json:"description"`
	TariffTypeCode      string             `json:"tariff_type_code"`
	Amount              pgtype.Int8        `json:"amount"`
	BillingIntervalCode pgtype.Text        `json:"billing_interval_code"`
	IntervalCount       pgtype.Int4        `json:"interval_count"`
	TierBrackets        []byte             `json:"tier_brackets"`
	IsActive            bool               `json:"is_active"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TariffType struct {
	TariffTypeCode string             `json:"tariff_type_code"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
