// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attempt.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    invoice_id,
    provider_code,
    internal_tx_id,
    amount_minor,
    currency,
    status,
    raw_request
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING attempt_id, created_at, updated_at
`

type CreatePaymentAttemptParams struct {
	InvoiceID    int64  `json:"invoice_id"`
	ProviderCode string `json:"provider_code"`
	InternalTxID string `json:"internal_tx_id"`
	AmountMinor  int64  `json:"amount_minor"`
	Currency     string `json:"currency"`
	Status       string `json:"status"`
	RawRequest   []byte `json:"raw_request"`
}

type CreatePaymentAttemptRow struct {
	AttemptID int64     `json:"attempt_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (CreatePaymentAttemptRow, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.InvoiceID,
		arg.ProviderCode,
		arg.InternalTxID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.RawRequest,
	)
	var i CreatePaymentAttemptRow
	err := row.Scan(&i.AttemptID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deletePaymentAttempt = `-- name: DeletePaymentAttempt :execresult
DELETE FROM payment_attempts
WHERE attempt_id = $1
`

func (q *Queries) DeletePaymentAttempt(ctx context.Context, attemptID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deletePaymentAttempt, attemptID)
}

const getPaymentAttemptByID = `-- name: GetPaymentAttemptByID :one
SELECT 
    attempt_id, invoice_id, provider_code, internal_tx_id, provider_tx_id, 
    amount_minor, currency, status, raw_response, raw_request, created_at, updated_at
FROM payment_attempts
WHERE attempt_id = $1
`

func (q *Queries) GetPaymentAttemptByID(ctx context.Context, attemptID int64) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByID, attemptID)
	var i PaymentAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.InvoiceID,
		&i.ProviderCode,
		&i.InternalTxID,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.RawRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByInternalTxID = `-- name: GetPaymentAttemptByInternalTxID :one
SELECT 
    attempt_id, invoice_id, provider_code, internal_tx_id, provider_tx_id, 
    amount_minor, currency, status, raw_response, raw_request, created_at, updated_at
FROM payment_attempts
WHERE internal_tx_id = $1
`

func (q *Queries) GetPaymentAttemptByInternalTxID(ctx context.Context, internalTxID string) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByInternalTxID, internalTxID)
	var i PaymentAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.InvoiceID,
		&i.ProviderCode,
		&i.InternalTxID,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.RawRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByProviderTxID = `-- name: GetPaymentAttemptByProviderTxID :one
SELECT 
    attempt_id, invoice_id, provider_code, internal_tx_id, provider_tx_id, 
    amount_minor, currency, status, raw_response, raw_request, created_at, updated_at
FROM payment_attempts
WHERE provider_tx_id = $1
`

func (q *Queries) GetPaymentAttemptByProviderTxID(ctx context.Context, providerTxID pgtype.Text) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByProviderTxID, providerTxID)
	var i PaymentAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.InvoiceID,
		&i.ProviderCode,
		&i.InternalTxID,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.RawRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingPaymentAttemptByInvoiceID = `-- name: GetPendingPaymentAttemptByInvoiceID :one
SELECT 
    attempt_id, invoice_id, provider_code, internal_tx_id, provider_tx_id, 
    amount_minor, currency, status, raw_response, raw_request, created_at, updated_at
FROM payment_attempts
WHERE invoice_id = $1 AND status = 'PENDING'
`

func (q *Queries) GetPendingPaymentAttemptByInvoiceID(ctx context.Context, invoiceID int64) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentAttemptByInvoiceID, invoiceID)
	var i PaymentAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.InvoiceID,
		&i.ProviderCode,
		&i.InternalTxID,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.RawRequest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAttemptsByInvoiceID = `-- name: ListPaymentAttemptsByInvoiceID :many
SELECT 
    attempt_id, invoice_id, provider_code, internal_tx_id, provider_tx_id, 
    amount_minor, currency, status, raw_response, raw_request, created_at, updated_at
FROM payment_attempts
WHERE invoice_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentAttemptsByInvoiceID(ctx context.Context, invoiceID int64) ([]PaymentAttempt, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAttempt
	for rows.Next() {
		var i PaymentAttempt
		if err := rows.Scan(
			&i.AttemptID,
			&i.InvoiceID,
			&i.ProviderCode,
			&i.InternalTxID,
			&i.ProviderTxID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.RawResponse,
			&i.RawRequest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAttemptResult = `-- name: UpdatePaymentAttemptResult :exec
UPDATE payment_attempts
SET 
    status = $2,
    provider_tx_id = COALESCE($3, provider_tx_id),
    raw_response = COALESCE($4, raw_response),
    updated_at = NOW()
WHERE attempt_id = $1
`

type UpdatePaymentAttemptResultParams struct {
	AttemptID    int64       `json:"attempt_id"`
	Status       string      `json:"status"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
	RawResponse  []byte      `json:"raw_response"`
}

func (q *Queries) UpdatePaymentAttemptResult(ctx context.Context, arg UpdatePaymentAttemptResultParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttemptResult,
		arg.AttemptID,
		arg.Status,
		arg.ProviderTxID,
		arg.RawResponse,
	)
	return err
}
