// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attempt.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAttempt = `-- name: CreatePaymentAttempt :one
INSERT INTO payment_attempts (
    invoice_id,
    attempt_number,
    idempotency_key,
    provider,
    provider_tx_id,
    amount_minor,
    currency,
    status,
    raw_response
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, created_at, updated_at
`

type CreatePaymentAttemptParams struct {
	InvoiceID      int64       `json:"invoice_id"`
	AttemptNumber  int32       `json:"attempt_number"`
	IdempotencyKey string      `json:"idempotency_key"`
	Provider       string      `json:"provider"`
	ProviderTxID   pgtype.Text `json:"provider_tx_id"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       string      `json:"currency"`
	Status         string      `json:"status"`
	RawResponse    []byte      `json:"raw_response"`
}

type CreatePaymentAttemptRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Inserts a new payment attempt.
// Will fail if another 'PENDING' attempt exists for this invoice_id
// or if (invoice_id, attempt_number) is duplicated.
func (q *Queries) CreatePaymentAttempt(ctx context.Context, arg CreatePaymentAttemptParams) (CreatePaymentAttemptRow, error) {
	row := q.db.QueryRow(ctx, createPaymentAttempt,
		arg.InvoiceID,
		arg.AttemptNumber,
		arg.IdempotencyKey,
		arg.Provider,
		arg.ProviderTxID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.RawResponse,
	)
	var i CreatePaymentAttemptRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getNextAttemptNumber = `-- name: GetNextAttemptNumber :one
SELECT COALESCE(MAX(attempt_number), 0) + 1 AS next_attempt_number
FROM payment_attempts
WHERE invoice_id = $1
`

// Computes the next attempt_number for an invoice (e.g., 0 -> 1, 1 -> 2).
func (q *Queries) GetNextAttemptNumber(ctx context.Context, invoiceID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getNextAttemptNumber, invoiceID)
	var next_attempt_number int32
	err := row.Scan(&next_attempt_number)
	return next_attempt_number, err
}

const getPaymentAttemptByID = `-- name: GetPaymentAttemptByID :one
SELECT 
    id, invoice_id, attempt_number, idempotency_key,
    provider, provider_tx_id, amount_minor, currency,
    status, raw_response, created_at, updated_at
FROM payment_attempts
WHERE id = $1
`

// Fetches a single attempt by its primary UUID.
func (q *Queries) GetPaymentAttemptByID(ctx context.Context, id uuid.UUID) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByID, id)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AttemptNumber,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByIdempotencyKey = `-- name: GetPaymentAttemptByIdempotencyKey :one
SELECT 
    id, invoice_id, attempt_number, idempotency_key,
    provider, provider_tx_id, amount_minor, currency,
    status, raw_response, created_at, updated_at
FROM payment_attempts
WHERE idempotency_key = $1
`

// Checks if an attempt with this idempotency key already exists.
func (q *Queries) GetPaymentAttemptByIdempotencyKey(ctx context.Context, idempotencyKey string) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByIdempotencyKey, idempotencyKey)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AttemptNumber,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentAttemptByProviderTxID = `-- name: GetPaymentAttemptByProviderTxID :one
SELECT 
    id, invoice_id, attempt_number, idempotency_key,
    provider, provider_tx_id, amount_minor, currency,
    status, raw_response, created_at, updated_at
FROM payment_attempts
WHERE provider = $1 AND provider_tx_id = $2
`

type GetPaymentAttemptByProviderTxIDParams struct {
	Provider     string      `json:"provider"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
}

// Used by Webhook handlers to find an attempt using the gateway's transaction reference.
func (q *Queries) GetPaymentAttemptByProviderTxID(ctx context.Context, arg GetPaymentAttemptByProviderTxIDParams) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPaymentAttemptByProviderTxID, arg.Provider, arg.ProviderTxID)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AttemptNumber,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingPaymentAttemptByInvoiceID = `-- name: GetPendingPaymentAttemptByInvoiceID :one
SELECT 
    id, invoice_id, attempt_number, idempotency_key,
    provider, provider_tx_id, amount_minor, currency,
    status, raw_response, created_at, updated_at
FROM payment_attempts
WHERE invoice_id = $1 AND status = 'PENDING'
`

// Checks if an invoice currently has an active 'PENDING' attempt.
func (q *Queries) GetPendingPaymentAttemptByInvoiceID(ctx context.Context, invoiceID int64) (PaymentAttempt, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentAttemptByInvoiceID, invoiceID)
	var i PaymentAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AttemptNumber,
		&i.IdempotencyKey,
		&i.Provider,
		&i.ProviderTxID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentAttemptsByInvoiceID = `-- name: ListPaymentAttemptsByInvoiceID :many
SELECT 
    id, invoice_id, attempt_number, idempotency_key,
    provider, provider_tx_id, amount_minor, currency,
    status, raw_response, created_at, updated_at
FROM payment_attempts
WHERE invoice_id = $1
ORDER BY attempt_number ASC
`

// Retrieves the full history of payment attempts for an invoice, ordered sequentially.
func (q *Queries) ListPaymentAttemptsByInvoiceID(ctx context.Context, invoiceID int64) ([]PaymentAttempt, error) {
	rows, err := q.db.Query(ctx, listPaymentAttemptsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAttempt
	for rows.Next() {
		var i PaymentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.AttemptNumber,
			&i.IdempotencyKey,
			&i.Provider,
			&i.ProviderTxID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAttemptStatus = `-- name: UpdatePaymentAttemptStatus :exec
UPDATE payment_attempts
SET 
    status = $2,
    provider_tx_id = COALESCE($3, provider_tx_id),
    raw_response = COALESCE($4, raw_response),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentAttemptStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
	RawResponse  []byte      `json:"raw_response"`
}

// Updates status, provider transaction ID, and optional raw payload response.
// Transitioning from 'PENDING' -> 'SUCCESS'/'FAILED' removes the row from the partial unique index.
func (q *Queries) UpdatePaymentAttemptStatus(ctx context.Context, arg UpdatePaymentAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttemptStatus,
		arg.ID,
		arg.Status,
		arg.ProviderTxID,
		arg.RawResponse,
	)
	return err
}
