// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    plan_code,
    version,
    effective_from,
    effective_until,
    legacy_price_policy_code,
    migration_path,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    plan_id,
    plan_code,
    version,
    effective_from,
    effective_until,
    legacy_price_policy_code,
    migration_path,
    metadata,
    created_at
`

type CreatePlanParams struct {
	PlanCode              string             `json:"plan_code"`
	Version               int32              `json:"version"`
	EffectiveFrom         time.Time          `json:"effective_from"`
	EffectiveUntil        pgtype.Timestamptz `json:"effective_until"`
	LegacyPricePolicyCode string             `json:"legacy_price_policy_code"`
	MigrationPath         []byte             `json:"migration_path"`
	Metadata              []byte             `json:"metadata"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.PlanCode,
		arg.Version,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.LegacyPricePolicyCode,
		arg.MigrationPath,
		arg.Metadata,
	)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.PlanCode,
		&i.Version,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.LegacyPricePolicyCode,
		&i.MigrationPath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createPlanDuration = `-- name: CreatePlanDuration :one
INSERT INTO plan_durations (
    plan_id,
    tariff_id,
    duration,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    plan_duration_id,
    plan_id,
    tariff_id,
    duration,
    is_active,
    created_at
`

type CreatePlanDurationParams struct {
	PlanID   int64 `json:"plan_id"`
	TariffID int64 `json:"tariff_id"`
	Duration int64 `json:"duration"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) CreatePlanDuration(ctx context.Context, arg CreatePlanDurationParams) (PlanDuration, error) {
	row := q.db.QueryRow(ctx, createPlanDuration,
		arg.PlanID,
		arg.TariffID,
		arg.Duration,
		arg.IsActive,
	)
	var i PlanDuration
	err := row.Scan(
		&i.PlanDurationID,
		&i.PlanID,
		&i.TariffID,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPlanVersion = `-- name: GetLatestPlanVersion :one
SELECT COALESCE(MAX(version), 0)::int
FROM plans
WHERE plan_code = $1
`

func (q *Queries) GetLatestPlanVersion(ctx context.Context, planCode string) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestPlanVersion, planCode)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlanByCodeAndVersion = `-- name: GetPlanByCodeAndVersion :one
SELECT
    plan_id,
    plan_code,
    version,
    effective_from,
    effective_until,
    legacy_price_policy_code,
    migration_path,
    metadata,
    created_at
FROM plans
WHERE plan_code = $1
  AND version = $2
`

type GetPlanByCodeAndVersionParams struct {
	PlanCode string `json:"plan_code"`
	Version  int32  `json:"version"`
}

func (q *Queries) GetPlanByCodeAndVersion(ctx context.Context, arg GetPlanByCodeAndVersionParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByCodeAndVersion, arg.PlanCode, arg.Version)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.PlanCode,
		&i.Version,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.LegacyPricePolicyCode,
		&i.MigrationPath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT plan_id, plan_code, version, effective_from, effective_until,
    legacy_price_policy_code, migration_path, metadata, created_at
FROM plans
WHERE plan_id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, planID int64) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, planID)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.PlanCode,
		&i.Version,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.LegacyPricePolicyCode,
		&i.MigrationPath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanDuration = `-- name: GetPlanDuration :one
SELECT
    plan_duration_id,
    plan_id,
    tariff_id,
    duration,
    is_active,
    created_at
FROM plan_durations
WHERE plan_duration_id = $1
`

func (q *Queries) GetPlanDuration(ctx context.Context, planDurationID int64) (PlanDuration, error) {
	row := q.db.QueryRow(ctx, getPlanDuration, planDurationID)
	var i PlanDuration
	err := row.Scan(
		&i.PlanDurationID,
		&i.PlanID,
		&i.TariffID,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanDurationByPlanAndDuration = `-- name: GetPlanDurationByPlanAndDuration :one
SELECT
    plan_duration_id,
    plan_id,
    tariff_id,
    duration,
    is_active,
    created_at
FROM plan_durations
WHERE plan_id = $1
  AND duration = $2
`

type GetPlanDurationByPlanAndDurationParams struct {
	PlanID   int64 `json:"plan_id"`
	Duration int64 `json:"duration"`
}

func (q *Queries) GetPlanDurationByPlanAndDuration(ctx context.Context, arg GetPlanDurationByPlanAndDurationParams) (PlanDuration, error) {
	row := q.db.QueryRow(ctx, getPlanDurationByPlanAndDuration, arg.PlanID, arg.Duration)
	var i PlanDuration
	err := row.Scan(
		&i.PlanDurationID,
		&i.PlanID,
		&i.TariffID,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanDurations = `-- name: ListPlanDurations :many
SELECT
    plan_duration_id,
    plan_id,
    tariff_id,
    duration,
    is_active,
    created_at
FROM plan_durations
WHERE plan_id = $1
ORDER BY plan_duration_id
`

func (q *Queries) ListPlanDurations(ctx context.Context, planID int64) ([]PlanDuration, error) {
	rows, err := q.db.Query(ctx, listPlanDurations, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanDuration
	for rows.Next() {
		var i PlanDuration
		if err := rows.Scan(
			&i.PlanDurationID,
			&i.PlanID,
			&i.TariffID,
			&i.Duration,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanVersions = `-- name: ListPlanVersions :many
SELECT
    plan_id,
    plan_code,
    version,
    effective_from,
    effective_until,
    legacy_price_policy_code,
    migration_path,
    metadata,
    created_at
FROM plans
WHERE plan_code = $1
ORDER BY version DESC
`

func (q *Queries) ListPlanVersions(ctx context.Context, planCode string) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlanVersions, planCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.PlanID,
			&i.PlanCode,
			&i.Version,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.LegacyPricePolicyCode,
			&i.MigrationPath,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT
    plan_id,
    plan_code,
    version,
    effective_from,
    effective_until,
    legacy_price_policy_code,
    migration_path,
    metadata,
    created_at
FROM plans
ORDER BY plan_id DESC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.PlanID,
			&i.PlanCode,
			&i.Version,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.LegacyPricePolicyCode,
			&i.MigrationPath,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanDurationTariff = `-- name: UpdatePlanDurationTariff :one
UPDATE plan_durations
SET
    tariff_id = $2,
    is_active = $3
WHERE plan_duration_id = $1
RETURNING
    plan_duration_id,
    plan_id,
    tariff_id,
    duration,
    is_active,
    created_at
`

type UpdatePlanDurationTariffParams struct {
	PlanDurationID int64 `json:"plan_duration_id"`
	TariffID       int64 `json:"tariff_id"`
	IsActive       bool  `json:"is_active"`
}

func (q *Queries) UpdatePlanDurationTariff(ctx context.Context, arg UpdatePlanDurationTariffParams) (PlanDuration, error) {
	row := q.db.QueryRow(ctx, updatePlanDurationTariff, arg.PlanDurationID, arg.TariffID, arg.IsActive)
	var i PlanDuration
	err := row.Scan(
		&i.PlanDurationID,
		&i.PlanID,
		&i.TariffID,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
