// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ppi_webhooks.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPPIWebhookStatus = `-- name: CheckPPIWebhookStatus :one
SELECT 
    (EXISTS (SELECT 1 FROM ppi_webhooks w1 WHERE w1.provider_code = $1 AND w1.provider_tx_id = $2))::boolean AS is_duplicate,
    (EXISTS (SELECT 1 FROM ppi_webhooks w2 WHERE w2.provider_code = $1 AND w2.provider_tx_id = $2 AND w2.published_at IS NOT NULL))::boolean AS is_published
`

type CheckPPIWebhookStatusParams struct {
	ProviderCode string      `json:"provider_code"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
}

type CheckPPIWebhookStatusRow struct {
	IsDuplicate bool `json:"is_duplicate"`
	IsPublished bool `json:"is_published"`
}

func (q *Queries) CheckPPIWebhookStatus(ctx context.Context, arg CheckPPIWebhookStatusParams) (CheckPPIWebhookStatusRow, error) {
	row := q.db.QueryRow(ctx, checkPPIWebhookStatus, arg.ProviderCode, arg.ProviderTxID)
	var i CheckPPIWebhookStatusRow
	err := row.Scan(&i.IsDuplicate, &i.IsPublished)
	return i, err
}

const getPPIWebhookByID = `-- name: GetPPIWebhookByID :one
SELECT webhook_id, provider_code, event_type, internal_tx_id, provider_tx_id, status, payload, published_at, processed_at
FROM ppi_webhooks
WHERE webhook_id = $1
`

func (q *Queries) GetPPIWebhookByID(ctx context.Context, webhookID string) (PpiWebhook, error) {
	row := q.db.QueryRow(ctx, getPPIWebhookByID, webhookID)
	var i PpiWebhook
	err := row.Scan(
		&i.WebhookID,
		&i.ProviderCode,
		&i.EventType,
		&i.InternalTxID,
		&i.ProviderTxID,
		&i.Status,
		&i.Payload,
		&i.PublishedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markPPIWebhookPublished = `-- name: MarkPPIWebhookPublished :exec
UPDATE ppi_webhooks
SET published_at = NOW()
WHERE webhook_id = $1
`

func (q *Queries) MarkPPIWebhookPublished(ctx context.Context, webhookID string) error {
	_, err := q.db.Exec(ctx, markPPIWebhookPublished, webhookID)
	return err
}

const savePPIWebhook = `-- name: SavePPIWebhook :exec
INSERT INTO ppi_webhooks (
    webhook_id, provider_code, event_type, internal_tx_id, provider_tx_id, status, payload, processed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (webhook_id) DO NOTHING
`

type SavePPIWebhookParams struct {
	WebhookID    string      `json:"webhook_id"`
	ProviderCode string      `json:"provider_code"`
	EventType    string      `json:"event_type"`
	InternalTxID pgtype.Text `json:"internal_tx_id"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
	Status       string      `json:"status"`
	Payload      []byte      `json:"payload"`
	ProcessedAt  time.Time   `json:"processed_at"`
}

func (q *Queries) SavePPIWebhook(ctx context.Context, arg SavePPIWebhookParams) error {
	_, err := q.db.Exec(ctx, savePPIWebhook,
		arg.WebhookID,
		arg.ProviderCode,
		arg.EventType,
		arg.InternalTxID,
		arg.ProviderTxID,
		arg.Status,
		arg.Payload,
		arg.ProcessedAt,
	)
	return err
}
