// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchasable_item.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchasableItem = `-- name: CreatePurchasableItem :one
INSERT INTO purchasable_items (
    item_code,
    item_type_code,
    name,
    description,
    plan_id,
    is_active,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    item_id,
    item_code,
    item_type_code,
    name,
    description,
    plan_id,
    is_active,
    metadata,
    created_at
`

type CreatePurchasableItemParams struct {
	ItemCode     string      `json:"item_code"`
	ItemTypeCode string      `json:"item_type_code"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PlanID       pgtype.Int8 `json:"plan_id"`
	IsActive     bool        `json:"is_active"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreatePurchasableItem(ctx context.Context, arg CreatePurchasableItemParams) (PurchasableItem, error) {
	row := q.db.QueryRow(ctx, createPurchasableItem,
		arg.ItemCode,
		arg.ItemTypeCode,
		arg.Name,
		arg.Description,
		arg.PlanID,
		arg.IsActive,
		arg.Metadata,
	)
	var i PurchasableItem
	err := row.Scan(
		&i.ItemID,
		&i.ItemCode,
		&i.ItemTypeCode,
		&i.Name,
		&i.Description,
		&i.PlanID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchasableItemByCode = `-- name: GetPurchasableItemByCode :one
SELECT
    item_id,
    item_code,
    item_type_code,
    name,
    description,
    plan_id,
    is_active,
    metadata,
    created_at
FROM purchasable_items
WHERE item_code = $1
`

func (q *Queries) GetPurchasableItemByCode(ctx context.Context, itemCode string) (PurchasableItem, error) {
	row := q.db.QueryRow(ctx, getPurchasableItemByCode, itemCode)
	var i PurchasableItem
	err := row.Scan(
		&i.ItemID,
		&i.ItemCode,
		&i.ItemTypeCode,
		&i.Name,
		&i.Description,
		&i.PlanID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchasableItemByID = `-- name: GetPurchasableItemByID :one
SELECT
    item_id,
    item_code,
    item_type_code,
    name,
    description,
    plan_id,
    is_active,
    metadata,
    created_at
FROM purchasable_items
WHERE item_id = $1
`

func (q *Queries) GetPurchasableItemByID(ctx context.Context, itemID int64) (PurchasableItem, error) {
	row := q.db.QueryRow(ctx, getPurchasableItemByID, itemID)
	var i PurchasableItem
	err := row.Scan(
		&i.ItemID,
		&i.ItemCode,
		&i.ItemTypeCode,
		&i.Name,
		&i.Description,
		&i.PlanID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchasableItems = `-- name: ListPurchasableItems :many
SELECT
    item_id,
    item_code,
    item_type_code,
    name,
    description,
    plan_id,
    is_active,
    metadata,
    created_at
FROM purchasable_items
ORDER BY item_id DESC
`

func (q *Queries) ListPurchasableItems(ctx context.Context) ([]PurchasableItem, error) {
	rows, err := q.db.Query(ctx, listPurchasableItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchasableItem
	for rows.Next() {
		var i PurchasableItem
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemCode,
			&i.ItemTypeCode,
			&i.Name,
			&i.Description,
			&i.PlanID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
