// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AppendEvent(ctx context.Context, arg AppendEventParams) (AppendEventRow, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (int64, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) error
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreatePlanDuration(ctx context.Context, arg CreatePlanDurationParams) (PlanDuration, error)
	// ============================================================================
	// FINE-GRAINED STATE & BALANCE TRANSITIONS
	// ============================================================================
	// Transitions DRAFT -> OPEN. Sets finalized_at timestamp.
	FinalizeInvoice(ctx context.Context, arg FinalizeInvoiceParams) (int64, error)
	GetInvoice(ctx context.Context, invoiceID int64) (GetInvoiceRow, error)
	GetLatestPlanVersion(ctx context.Context, planCode string) (int32, error)
	GetPlanByCodeAndVersion(ctx context.Context, arg GetPlanByCodeAndVersionParams) (Plan, error)
	GetPlanDurations(ctx context.Context, planID int64) ([]PlanDuration, error)
	ListInvoiceLineItems(ctx context.Context, invoiceID int64) ([]ListInvoiceLineItemsRow, error)
	// Transitions -> PAID. Updates amounts and sets paid_at timestamp.
	MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error)
	ReadStream(ctx context.Context, arg ReadStreamParams) ([]ReadStreamRow, error)
	ReadStreamFrom(ctx context.Context, arg ReadStreamFromParams) ([]ReadStreamFromRow, error)
	// Updates balance details (partial payments, dunning adjustments) without touching status code.
	UpdatePaymentBalances(ctx context.Context, arg UpdatePaymentBalancesParams) (int64, error)
	// Transitions -> VOID. Leaves balances intact for historical audit.
	VoidInvoice(ctx context.Context, arg VoidInvoiceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
