// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statemachine.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxRows = `-- name: ClaimOutboxRows :many
WITH candidates AS (
    SELECT outbox_id
    FROM sm_action_outbox
    WHERE status = 'PENDING'
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE sm_action_outbox o
SET status = 'PROCESSING',
    claimed_at = now(),
    claimed_by = $2,
    attempts = attempts + 1
FROM candidates c
WHERE o.outbox_id = c.outbox_id
RETURNING o.outbox_id, o.instance_id, o.history_id, o.binding_id, o.action_name, o.params,
          o.status, o.attempts, o.claimed_at, o.claimed_by, o.last_error, o.created_at
`

type ClaimOutboxRowsParams struct {
	Limit     int32       `json:"limit"`
	ClaimedBy pgtype.Text `json:"claimed_by"`
}

func (q *Queries) ClaimOutboxRows(ctx context.Context, arg ClaimOutboxRowsParams) ([]SmActionOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxRows, arg.Limit, arg.ClaimedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmActionOutbox
	for rows.Next() {
		var i SmActionOutbox
		if err := rows.Scan(
			&i.OutboxID,
			&i.InstanceID,
			&i.HistoryID,
			&i.BindingID,
			&i.ActionName,
			&i.Params,
			&i.Status,
			&i.Attempts,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimScheduledTransitions = `-- name: ClaimScheduledTransitions :many
WITH candidates AS (
    SELECT schedule_id
    FROM sm_scheduled_transitions
    WHERE status = 'PENDING' AND fire_at <= now()
    ORDER BY fire_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE sm_scheduled_transitions s
SET status = 'PROCESSING',
    claimed_at = now(),
    claimed_by = $2,
    attempts = attempts + 1
FROM candidates c
WHERE s.schedule_id = c.schedule_id
RETURNING s.schedule_id, s.instance_id, s.event_name, s.event_payload, s.fire_at, s.status,
          s.attempts, s.claimed_at, s.claimed_by, s.last_error, s.created_at
`

type ClaimScheduledTransitionsParams struct {
	Limit     int32       `json:"limit"`
	ClaimedBy pgtype.Text `json:"claimed_by"`
}

func (q *Queries) ClaimScheduledTransitions(ctx context.Context, arg ClaimScheduledTransitionsParams) ([]SmScheduledTransition, error) {
	rows, err := q.db.Query(ctx, claimScheduledTransitions, arg.Limit, arg.ClaimedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmScheduledTransition
	for rows.Next() {
		var i SmScheduledTransition
		if err := rows.Scan(
			&i.ScheduleID,
			&i.InstanceID,
			&i.EventName,
			&i.EventPayload,
			&i.FireAt,
			&i.Status,
			&i.Attempts,
			&i.ClaimedAt,
			&i.ClaimedBy,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO sm_instances (
    definition_id,
    machine_type,
    subject_type,
    subject_id,
    current_state,
    context
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING instance_id, version, status, created_at, updated_at
`

type CreateInstanceParams struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	MachineType  string    `json:"machine_type"`
	SubjectType  string    `json:"subject_type"`
	SubjectID    string    `json:"subject_id"`
	CurrentState string    `json:"current_state"`
	Context      []byte    `json:"context"`
}

type CreateInstanceRow struct {
	InstanceID uuid.UUID `json:"instance_id"`
	Version    int64     `json:"version"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.DefinitionID,
		arg.MachineType,
		arg.SubjectType,
		arg.SubjectID,
		arg.CurrentState,
		arg.Context,
	)
	var i CreateInstanceRow
	err := row.Scan(
		&i.InstanceID,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDefinitionsForMachineType = `-- name: DeactivateDefinitionsForMachineType :exec
UPDATE sm_definitions
SET is_active = false
WHERE machine_type = $1 AND is_active
`

func (q *Queries) DeactivateDefinitionsForMachineType(ctx context.Context, machineType string) error {
	_, err := q.db.Exec(ctx, deactivateDefinitionsForMachineType, machineType)
	return err
}

const finalizeTransitionHistory = `-- name: FinalizeTransitionHistory :exec
UPDATE sm_transition_history
SET context_after = $2
WHERE history_id = $1
`

type FinalizeTransitionHistoryParams struct {
	HistoryID    int64  `json:"history_id"`
	ContextAfter []byte `json:"context_after"`
}

func (q *Queries) FinalizeTransitionHistory(ctx context.Context, arg FinalizeTransitionHistoryParams) error {
	_, err := q.db.Exec(ctx, finalizeTransitionHistory, arg.HistoryID, arg.ContextAfter)
	return err
}

const getActiveDefinition = `-- name: GetActiveDefinition :one
SELECT definition_id, machine_type, version, initial_state, is_active, created_at
FROM sm_definitions
WHERE machine_type = $1 AND is_active
`

func (q *Queries) GetActiveDefinition(ctx context.Context, machineType string) (SmDefinition, error) {
	row := q.db.QueryRow(ctx, getActiveDefinition, machineType)
	var i SmDefinition
	err := row.Scan(
		&i.DefinitionID,
		&i.MachineType,
		&i.Version,
		&i.InitialState,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDefinitionByID = `-- name: GetDefinitionByID :one
SELECT definition_id, machine_type, version, initial_state, is_active, created_at
FROM sm_definitions
WHERE definition_id = $1
`

func (q *Queries) GetDefinitionByID(ctx context.Context, definitionID uuid.UUID) (SmDefinition, error) {
	row := q.db.QueryRow(ctx, getDefinitionByID, definitionID)
	var i SmDefinition
	err := row.Scan(
		&i.DefinitionID,
		&i.MachineType,
		&i.Version,
		&i.InitialState,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getInstanceByID = `-- name: GetInstanceByID :one
SELECT instance_id, definition_id, machine_type, subject_type, subject_id, current_state,
       context, version, status, created_at, updated_at
FROM sm_instances
WHERE instance_id = $1
`

func (q *Queries) GetInstanceByID(ctx context.Context, instanceID uuid.UUID) (SmInstance, error) {
	row := q.db.QueryRow(ctx, getInstanceByID, instanceID)
	var i SmInstance
	err := row.Scan(
		&i.InstanceID,
		&i.DefinitionID,
		&i.MachineType,
		&i.SubjectType,
		&i.SubjectID,
		&i.CurrentState,
		&i.Context,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceBySubject = `-- name: GetInstanceBySubject :one
SELECT instance_id, definition_id, machine_type, subject_type, subject_id, current_state,
       context, version, status, created_at, updated_at
FROM sm_instances
WHERE subject_type = $1 AND subject_id = $2 AND machine_type = $3
`

type GetInstanceBySubjectParams struct {
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
	MachineType string `json:"machine_type"`
}

func (q *Queries) GetInstanceBySubject(ctx context.Context, arg GetInstanceBySubjectParams) (SmInstance, error) {
	row := q.db.QueryRow(ctx, getInstanceBySubject, arg.SubjectType, arg.SubjectID, arg.MachineType)
	var i SmInstance
	err := row.Scan(
		&i.InstanceID,
		&i.DefinitionID,
		&i.MachineType,
		&i.SubjectType,
		&i.SubjectID,
		&i.CurrentState,
		&i.Context,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceForUpdate = `-- name: GetInstanceForUpdate :one
SELECT instance_id, definition_id, machine_type, subject_type, subject_id, current_state,
       context, version, status, created_at, updated_at
FROM sm_instances
WHERE instance_id = $1
FOR UPDATE
`

func (q *Queries) GetInstanceForUpdate(ctx context.Context, instanceID uuid.UUID) (SmInstance, error) {
	row := q.db.QueryRow(ctx, getInstanceForUpdate, instanceID)
	var i SmInstance
	err := row.Scan(
		&i.InstanceID,
		&i.DefinitionID,
		&i.MachineType,
		&i.SubjectType,
		&i.SubjectID,
		&i.CurrentState,
		&i.Context,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActionBinding = `-- name: InsertActionBinding :one
INSERT INTO sm_action_bindings (
    definition_id,
    hook_type,
    state_name,
    transition_id,
    seq,
    action_name,
    params_kind,
    params,
    params_script,
    mode,
    on_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING binding_id
`

type InsertActionBindingParams struct {
	DefinitionID uuid.UUID   `json:"definition_id"`
	HookType     string      `json:"hook_type"`
	StateName    pgtype.Text `json:"state_name"`
	TransitionID *uuid.UUID  `json:"transition_id"`
	Seq          int32       `json:"seq"`
	ActionName   string      `json:"action_name"`
	ParamsKind   string      `json:"params_kind"`
	Params       []byte      `json:"params"`
	ParamsScript pgtype.Text `json:"params_script"`
	Mode         string      `json:"mode"`
	OnError      string      `json:"on_error"`
}

func (q *Queries) InsertActionBinding(ctx context.Context, arg InsertActionBindingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertActionBinding,
		arg.DefinitionID,
		arg.HookType,
		arg.StateName,
		arg.TransitionID,
		arg.Seq,
		arg.ActionName,
		arg.ParamsKind,
		arg.Params,
		arg.ParamsScript,
		arg.Mode,
		arg.OnError,
	)
	var binding_id uuid.UUID
	err := row.Scan(&binding_id)
	return binding_id, err
}

const insertDefinition = `-- name: InsertDefinition :one
INSERT INTO sm_definitions (
    machine_type,
    version,
    initial_state,
    is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING definition_id, created_at
`

type InsertDefinitionParams struct {
	MachineType  string `json:"machine_type"`
	Version      int32  `json:"version"`
	InitialState string `json:"initial_state"`
	IsActive     bool   `json:"is_active"`
}

type InsertDefinitionRow struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) InsertDefinition(ctx context.Context, arg InsertDefinitionParams) (InsertDefinitionRow, error) {
	row := q.db.QueryRow(ctx, insertDefinition,
		arg.MachineType,
		arg.Version,
		arg.InitialState,
		arg.IsActive,
	)
	var i InsertDefinitionRow
	err := row.Scan(&i.DefinitionID, &i.CreatedAt)
	return i, err
}

const insertGuardBinding = `-- name: InsertGuardBinding :exec
INSERT INTO sm_guard_bindings (
    transition_id,
    seq,
    implementation_kind,
    guard_name,
    script,
    params
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertGuardBindingParams struct {
	TransitionID       uuid.UUID   `json:"transition_id"`
	Seq                int32       `json:"seq"`
	ImplementationKind string      `json:"implementation_kind"`
	GuardName          pgtype.Text `json:"guard_name"`
	Script             pgtype.Text `json:"script"`
	Params             []byte      `json:"params"`
}

func (q *Queries) InsertGuardBinding(ctx context.Context, arg InsertGuardBindingParams) error {
	_, err := q.db.Exec(ctx, insertGuardBinding,
		arg.TransitionID,
		arg.Seq,
		arg.ImplementationKind,
		arg.GuardName,
		arg.Script,
		arg.Params,
	)
	return err
}

const insertOutboxRow = `-- name: InsertOutboxRow :exec
INSERT INTO sm_action_outbox (
    instance_id,
    history_id,
    binding_id,
    action_name,
    params
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertOutboxRowParams struct {
	InstanceID uuid.UUID   `json:"instance_id"`
	HistoryID  pgtype.Int8 `json:"history_id"`
	BindingID  *uuid.UUID  `json:"binding_id"`
	ActionName string      `json:"action_name"`
	Params     []byte      `json:"params"`
}

func (q *Queries) InsertOutboxRow(ctx context.Context, arg InsertOutboxRowParams) error {
	_, err := q.db.Exec(ctx, insertOutboxRow,
		arg.InstanceID,
		arg.HistoryID,
		arg.BindingID,
		arg.ActionName,
		arg.Params,
	)
	return err
}

const insertScheduledTransition = `-- name: InsertScheduledTransition :one
INSERT INTO sm_scheduled_transitions (
    instance_id,
    event_name,
    event_payload,
    fire_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING schedule_id
`

type InsertScheduledTransitionParams struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	EventName    string    `json:"event_name"`
	EventPayload []byte    `json:"event_payload"`
	FireAt       time.Time `json:"fire_at"`
}

func (q *Queries) InsertScheduledTransition(ctx context.Context, arg InsertScheduledTransitionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertScheduledTransition,
		arg.InstanceID,
		arg.EventName,
		arg.EventPayload,
		arg.FireAt,
	)
	var schedule_id uuid.UUID
	err := row.Scan(&schedule_id)
	return schedule_id, err
}

const insertState = `-- name: InsertState :exec
INSERT INTO sm_states (
    definition_id,
    state_name,
    is_final,
    metadata
) VALUES (
    $1, $2, $3, $4
)
`

type InsertStateParams struct {
	DefinitionID uuid.UUID `json:"definition_id"`
	StateName    string    `json:"state_name"`
	IsFinal      bool      `json:"is_final"`
	Metadata     []byte    `json:"metadata"`
}

func (q *Queries) InsertState(ctx context.Context, arg InsertStateParams) error {
	_, err := q.db.Exec(ctx, insertState,
		arg.DefinitionID,
		arg.StateName,
		arg.IsFinal,
		arg.Metadata,
	)
	return err
}

const insertTransition = `-- name: InsertTransition :one
INSERT INTO sm_transitions (
    definition_id,
    from_state,
    event_name,
    to_state,
    priority,
    emit_event_type
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING transition_id
`

type InsertTransitionParams struct {
	DefinitionID  uuid.UUID   `json:"definition_id"`
	FromState     string      `json:"from_state"`
	EventName     string      `json:"event_name"`
	ToState       string      `json:"to_state"`
	Priority      int32       `json:"priority"`
	EmitEventType pgtype.Text `json:"emit_event_type"`
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransition,
		arg.DefinitionID,
		arg.FromState,
		arg.EventName,
		arg.ToState,
		arg.Priority,
		arg.EmitEventType,
	)
	var transition_id uuid.UUID
	err := row.Scan(&transition_id)
	return transition_id, err
}

const insertTransitionHistoryPending = `-- name: InsertTransitionHistoryPending :one
INSERT INTO sm_transition_history (
    instance_id,
    transition_id,
    from_state,
    to_state,
    event_name,
    event_payload,
    context_before,
    triggered_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING history_id, occurred_at
`

type InsertTransitionHistoryPendingParams struct {
	InstanceID    uuid.UUID   `json:"instance_id"`
	TransitionID  *uuid.UUID  `json:"transition_id"`
	FromState     pgtype.Text `json:"from_state"`
	ToState       string      `json:"to_state"`
	EventName     pgtype.Text `json:"event_name"`
	EventPayload  []byte      `json:"event_payload"`
	ContextBefore []byte      `json:"context_before"`
	TriggeredBy   pgtype.Text `json:"triggered_by"`
}

type InsertTransitionHistoryPendingRow struct {
	HistoryID  int64     `json:"history_id"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) InsertTransitionHistoryPending(ctx context.Context, arg InsertTransitionHistoryPendingParams) (InsertTransitionHistoryPendingRow, error) {
	row := q.db.QueryRow(ctx, insertTransitionHistoryPending,
		arg.InstanceID,
		arg.TransitionID,
		arg.FromState,
		arg.ToState,
		arg.EventName,
		arg.EventPayload,
		arg.ContextBefore,
		arg.TriggeredBy,
	)
	var i InsertTransitionHistoryPendingRow
	err := row.Scan(&i.HistoryID, &i.OccurredAt)
	return i, err
}

const listActionBindingsByDefinition = `-- name: ListActionBindingsByDefinition :many
SELECT binding_id, definition_id, hook_type, state_name, transition_id, seq, action_name,
       params_kind, params, params_script, mode, on_error
FROM sm_action_bindings
WHERE definition_id = $1
`

func (q *Queries) ListActionBindingsByDefinition(ctx context.Context, definitionID uuid.UUID) ([]SmActionBinding, error) {
	rows, err := q.db.Query(ctx, listActionBindingsByDefinition, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmActionBinding
	for rows.Next() {
		var i SmActionBinding
		if err := rows.Scan(
			&i.BindingID,
			&i.DefinitionID,
			&i.HookType,
			&i.StateName,
			&i.TransitionID,
			&i.Seq,
			&i.ActionName,
			&i.ParamsKind,
			&i.Params,
			&i.ParamsScript,
			&i.Mode,
			&i.OnError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardBindingsByDefinition = `-- name: ListGuardBindingsByDefinition :many
SELECT gb.transition_id, gb.seq, gb.implementation_kind, gb.guard_name, gb.script, gb.params
FROM sm_guard_bindings gb
JOIN sm_transitions t ON t.transition_id = gb.transition_id
WHERE t.definition_id = $1
`

func (q *Queries) ListGuardBindingsByDefinition(ctx context.Context, definitionID uuid.UUID) ([]SmGuardBinding, error) {
	rows, err := q.db.Query(ctx, listGuardBindingsByDefinition, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmGuardBinding
	for rows.Next() {
		var i SmGuardBinding
		if err := rows.Scan(
			&i.TransitionID,
			&i.Seq,
			&i.ImplementationKind,
			&i.GuardName,
			&i.Script,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesByDefinition = `-- name: ListStatesByDefinition :many
SELECT definition_id, state_name, is_final, metadata
FROM sm_states
WHERE definition_id = $1
`

func (q *Queries) ListStatesByDefinition(ctx context.Context, definitionID uuid.UUID) ([]SmState, error) {
	rows, err := q.db.Query(ctx, listStatesByDefinition, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmState
	for rows.Next() {
		var i SmState
		if err := rows.Scan(
			&i.DefinitionID,
			&i.StateName,
			&i.IsFinal,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitionsByDefinition = `-- name: ListTransitionsByDefinition :many
SELECT transition_id, definition_id, from_state, event_name, to_state, priority, emit_event_type
FROM sm_transitions
WHERE definition_id = $1
`

func (q *Queries) ListTransitionsByDefinition(ctx context.Context, definitionID uuid.UUID) ([]SmTransition, error) {
	rows, err := q.db.Query(ctx, listTransitionsByDefinition, definitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmTransition
	for rows.Next() {
		var i SmTransition
		if err := rows.Scan(
			&i.TransitionID,
			&i.DefinitionID,
			&i.FromState,
			&i.EventName,
			&i.ToState,
			&i.Priority,
			&i.EmitEventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE sm_action_outbox
SET status = 'FAILED',
    last_error = $2
WHERE outbox_id = $1
`

type MarkOutboxFailedParams struct {
	OutboxID  int64       `json:"outbox_id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.OutboxID, arg.LastError)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE sm_action_outbox
SET status = 'PUBLISHED'
WHERE outbox_id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, outboxID int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, outboxID)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE sm_action_outbox
SET status = 'PENDING',
    last_error = $2
WHERE outbox_id = $1
`

type MarkOutboxRetryParams struct {
	OutboxID  int64       `json:"outbox_id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.OutboxID, arg.LastError)
	return err
}

const markScheduleFailed = `-- name: MarkScheduleFailed :exec
UPDATE sm_scheduled_transitions
SET status = 'FAILED',
    last_error = $2
WHERE schedule_id = $1
`

type MarkScheduleFailedParams struct {
	ScheduleID uuid.UUID   `json:"schedule_id"`
	LastError  pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkScheduleFailed(ctx context.Context, arg MarkScheduleFailedParams) error {
	_, err := q.db.Exec(ctx, markScheduleFailed, arg.ScheduleID, arg.LastError)
	return err
}

const markScheduleFired = `-- name: MarkScheduleFired :exec
UPDATE sm_scheduled_transitions
SET status = 'FIRED'
WHERE schedule_id = $1
`

func (q *Queries) MarkScheduleFired(ctx context.Context, scheduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScheduleFired, scheduleID)
	return err
}

const markScheduleRetry = `-- name: MarkScheduleRetry :exec
UPDATE sm_scheduled_transitions
SET status = 'PENDING',
    last_error = $2
WHERE schedule_id = $1
`

type MarkScheduleRetryParams struct {
	ScheduleID uuid.UUID   `json:"schedule_id"`
	LastError  pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkScheduleRetry(ctx context.Context, arg MarkScheduleRetryParams) error {
	_, err := q.db.Exec(ctx, markScheduleRetry, arg.ScheduleID, arg.LastError)
	return err
}

const reapStuckOutbox = `-- name: ReapStuckOutbox :execrows
UPDATE sm_action_outbox
SET status = 'PENDING'
WHERE status = 'PROCESSING' AND claimed_at < $1
`

func (q *Queries) ReapStuckOutbox(ctx context.Context, claimedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reapStuckOutbox, claimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapStuckSchedules = `-- name: ReapStuckSchedules :execrows
UPDATE sm_scheduled_transitions
SET status = 'PENDING'
WHERE status = 'PROCESSING' AND claimed_at < $1
`

func (q *Queries) ReapStuckSchedules(ctx context.Context, claimedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reapStuckSchedules, claimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstanceState = `-- name: UpdateInstanceState :execrows
UPDATE sm_instances
SET current_state = $3,
    context = $4,
    status = $5,
    version = version + 1,
    updated_at = now()
WHERE instance_id = $1 AND version = $2
`

type UpdateInstanceStateParams struct {
	InstanceID   uuid.UUID `json:"instance_id"`
	Version      int64     `json:"version"`
	CurrentState string    `json:"current_state"`
	Context      []byte    `json:"context"`
	Status       string    `json:"status"`
}

func (q *Queries) UpdateInstanceState(ctx context.Context, arg UpdateInstanceStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstanceState,
		arg.InstanceID,
		arg.Version,
		arg.CurrentState,
		arg.Context,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
