// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor)
VALUES ($1, $2, $3, 'ACTIVE', $4, $5, $6)
RETURNING subscription_id, version, account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor, canceled_at, ended_at
`

type CreateSubscriptionParams struct {
	AccountID            int64     `json:"account_id"`
	PlanID               int64     `json:"plan_id"`
	PlanVersion          int32     `json:"plan_version"`
	CurrentPeriodStartAt time.Time `json:"current_period_start_at"`
	CurrentPeriodEndAt   time.Time `json:"current_period_end_at"`
	BillingCycleAnchor   time.Time `json:"billing_cycle_anchor"`
}

type CreateSubscriptionRow struct {
	SubscriptionID         int64              `json:"subscription_id"`
	Version                int64              `json:"version"`
	AccountID              int64              `json:"account_id"`
	PlanID                 int64              `json:"plan_id"`
	PlanVersion            int32              `json:"plan_version"`
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	CurrentPeriodStartAt   time.Time          `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time          `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time          `json:"billing_cycle_anchor"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.AccountID,
		arg.PlanID,
		arg.PlanVersion,
		arg.CurrentPeriodStartAt,
		arg.CurrentPeriodEndAt,
		arg.BillingCycleAnchor,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.SubscriptionID,
		&i.Version,
		&i.AccountID,
		&i.PlanID,
		&i.PlanVersion,
		&i.SubscriptionStatusCode,
		&i.CurrentPeriodStartAt,
		&i.CurrentPeriodEndAt,
		&i.BillingCycleAnchor,
		&i.CanceledAt,
		&i.EndedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT subscription_id, version, account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor, canceled_at, ended_at FROM subscriptions WHERE subscription_id = $1
`

type GetSubscriptionRow struct {
	SubscriptionID         int64              `json:"subscription_id"`
	Version                int64              `json:"version"`
	AccountID              int64              `json:"account_id"`
	PlanID                 int64              `json:"plan_id"`
	PlanVersion            int32              `json:"plan_version"`
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	CurrentPeriodStartAt   time.Time          `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time          `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time          `json:"billing_cycle_anchor"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) GetSubscription(ctx context.Context, subscriptionID int64) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, subscriptionID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.SubscriptionID,
		&i.Version,
		&i.AccountID,
		&i.PlanID,
		&i.PlanVersion,
		&i.SubscriptionStatusCode,
		&i.CurrentPeriodStartAt,
		&i.CurrentPeriodEndAt,
		&i.BillingCycleAnchor,
		&i.CanceledAt,
		&i.EndedAt,
	)
	return i, err
}

const listAccountSubscriptions = `-- name: ListAccountSubscriptions :many
SELECT subscription_id, version, account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor, canceled_at, ended_at
FROM subscriptions 
WHERE account_id = $1 AND subscription_status_code = 'ACTIVE'
`

type ListAccountSubscriptionsRow struct {
	SubscriptionID         int64              `json:"subscription_id"`
	Version                int64              `json:"version"`
	AccountID              int64              `json:"account_id"`
	PlanID                 int64              `json:"plan_id"`
	PlanVersion            int32              `json:"plan_version"`
	SubscriptionStatusCode string             `json:"subscription_status_code"`
	CurrentPeriodStartAt   time.Time          `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time          `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time          `json:"billing_cycle_anchor"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) ListAccountSubscriptions(ctx context.Context, accountID int64) ([]ListAccountSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAccountSubscriptions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountSubscriptionsRow
	for rows.Next() {
		var i ListAccountSubscriptionsRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.Version,
			&i.AccountID,
			&i.PlanID,
			&i.PlanVersion,
			&i.SubscriptionStatusCode,
			&i.CurrentPeriodStartAt,
			&i.CurrentPeriodEndAt,
			&i.BillingCycleAnchor,
			&i.CanceledAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
