// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor)
VALUES ($1, $2, $3, 'ACTIVE', $4, $5, $6)
RETURNING subscription_id, account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor
`

type CreateSubscriptionParams struct {
	AccountID            int64     `json:"account_id"`
	PlanID               int64     `json:"plan_id"`
	PlanVersion          int32     `json:"plan_version"`
	CurrentPeriodStartAt time.Time `json:"current_period_start_at"`
	CurrentPeriodEndAt   time.Time `json:"current_period_end_at"`
	BillingCycleAnchor   time.Time `json:"billing_cycle_anchor"`
}

type CreateSubscriptionRow struct {
	SubscriptionID         int64     `json:"subscription_id"`
	AccountID              int64     `json:"account_id"`
	PlanID                 int64     `json:"plan_id"`
	PlanVersion            int32     `json:"plan_version"`
	SubscriptionStatusCode string    `json:"subscription_status_code"`
	CurrentPeriodStartAt   time.Time `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time `json:"billing_cycle_anchor"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.AccountID,
		arg.PlanID,
		arg.PlanVersion,
		arg.CurrentPeriodStartAt,
		arg.CurrentPeriodEndAt,
		arg.BillingCycleAnchor,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.SubscriptionID,
		&i.AccountID,
		&i.PlanID,
		&i.PlanVersion,
		&i.SubscriptionStatusCode,
		&i.CurrentPeriodStartAt,
		&i.CurrentPeriodEndAt,
		&i.BillingCycleAnchor,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT subscription_id, account_id, plan_id, plan_version, subscription_status_code, current_period_start_at, current_period_end_at, billing_cycle_anchor FROM subscriptions WHERE subscription_id = $1
`

type GetSubscriptionRow struct {
	SubscriptionID         int64     `json:"subscription_id"`
	AccountID              int64     `json:"account_id"`
	PlanID                 int64     `json:"plan_id"`
	PlanVersion            int32     `json:"plan_version"`
	SubscriptionStatusCode string    `json:"subscription_status_code"`
	CurrentPeriodStartAt   time.Time `json:"current_period_start_at"`
	CurrentPeriodEndAt     time.Time `json:"current_period_end_at"`
	BillingCycleAnchor     time.Time `json:"billing_cycle_anchor"`
}

func (q *Queries) GetSubscription(ctx context.Context, subscriptionID int64) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, subscriptionID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.SubscriptionID,
		&i.AccountID,
		&i.PlanID,
		&i.PlanVersion,
		&i.SubscriptionStatusCode,
		&i.CurrentPeriodStartAt,
		&i.CurrentPeriodEndAt,
		&i.BillingCycleAnchor,
	)
	return i, err
}
