// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tariff.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTariff = `-- name: CreateTariff :one

WITH locked AS (
    SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
),
next_version AS (
    SELECT COALESCE(MAX(version), 0) + 1 AS version
    FROM tariffs, locked
    WHERE tariff_code = $1
)

INSERT INTO tariffs (
    tariff_code,
    version,
    name,
    description,
    tariff_type_code,
    tier_strategy,
    quantity_unit,
    amount,
    currency,
    tier_brackets,
    is_active,
    metadata
)

SELECT
    $1,
    next_version.version,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11

FROM next_version

RETURNING
    tariff_id,
    tariff_code,
    version,
    name,
    description,
    tariff_type_code,
    tier_strategy,
    quantity_unit,
    amount,
    currency,
    tier_brackets,
    is_active,
    metadata,
    created_at
`

type CreateTariffParams struct {
	TariffCode     string      `json:"tariff_code"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	TierStrategy   pgtype.Text `json:"tier_strategy"`
	QuantityUnit   pgtype.Text `json:"quantity_unit"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
}

type CreateTariffRow struct {
	TariffID       int64       `json:"tariff_id"`
	TariffCode     string      `json:"tariff_code"`
	Version        int32       `json:"version"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	TierStrategy   pgtype.Text `json:"tier_strategy"`
	QuantityUnit   pgtype.Text `json:"quantity_unit"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) CreateTariff(ctx context.Context, arg CreateTariffParams) (CreateTariffRow, error) {
	row := q.db.QueryRow(ctx, createTariff,
		arg.TariffCode,
		arg.Name,
		arg.Description,
		arg.TariffTypeCode,
		arg.TierStrategy,
		arg.QuantityUnit,
		arg.Amount,
		arg.Currency,
		arg.TierBrackets,
		arg.IsActive,
		arg.Metadata,
	)
	var i CreateTariffRow
	err := row.Scan(
		&i.TariffID,
		&i.TariffCode,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.TariffTypeCode,
		&i.TierStrategy,
		&i.QuantityUnit,
		&i.Amount,
		&i.Currency,
		&i.TierBrackets,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTariffVersion = `-- name: GetLatestTariffVersion :one
SELECT COALESCE(MAX(version), 0)::int
FROM tariffs
WHERE tariff_code = $1
`

func (q *Queries) GetLatestTariffVersion(ctx context.Context, tariffCode string) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestTariffVersion, tariffCode)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTariffByCodeAndVersion = `-- name: GetTariffByCodeAndVersion :one
SELECT
    tariff_id,
    tariff_code,
    version,
    name,
    description,
    tariff_type_code,
    tier_strategy,
    quantity_unit,
    amount,
    currency,
    tier_brackets,
    is_active,
    metadata,
    created_at
FROM tariffs
WHERE tariff_code = $1
  AND version = $2
`

type GetTariffByCodeAndVersionParams struct {
	TariffCode string `json:"tariff_code"`
	Version    int32  `json:"version"`
}

type GetTariffByCodeAndVersionRow struct {
	TariffID       int64       `json:"tariff_id"`
	TariffCode     string      `json:"tariff_code"`
	Version        int32       `json:"version"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	TierStrategy   pgtype.Text `json:"tier_strategy"`
	QuantityUnit   pgtype.Text `json:"quantity_unit"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) GetTariffByCodeAndVersion(ctx context.Context, arg GetTariffByCodeAndVersionParams) (GetTariffByCodeAndVersionRow, error) {
	row := q.db.QueryRow(ctx, getTariffByCodeAndVersion, arg.TariffCode, arg.Version)
	var i GetTariffByCodeAndVersionRow
	err := row.Scan(
		&i.TariffID,
		&i.TariffCode,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.TariffTypeCode,
		&i.TierStrategy,
		&i.QuantityUnit,
		&i.Amount,
		&i.Currency,
		&i.TierBrackets,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTariffByID = `-- name: GetTariffByID :one
SELECT
    tariff_id,
    tariff_code,
    version,
    name,
    description,
    tariff_type_code,
    tier_strategy,
    quantity_unit,
    amount,
    currency,
    tier_brackets,
    is_active,
    metadata,
    created_at
FROM tariffs
WHERE tariff_id = $1
`

type GetTariffByIDRow struct {
	TariffID       int64       `json:"tariff_id"`
	TariffCode     string      `json:"tariff_code"`
	Version        int32       `json:"version"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	TierStrategy   pgtype.Text `json:"tier_strategy"`
	QuantityUnit   pgtype.Text `json:"quantity_unit"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) GetTariffByID(ctx context.Context, tariffID int64) (GetTariffByIDRow, error) {
	row := q.db.QueryRow(ctx, getTariffByID, tariffID)
	var i GetTariffByIDRow
	err := row.Scan(
		&i.TariffID,
		&i.TariffCode,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.TariffTypeCode,
		&i.TierStrategy,
		&i.QuantityUnit,
		&i.Amount,
		&i.Currency,
		&i.TierBrackets,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listTariffVersions = `-- name: ListTariffVersions :many
SELECT
    tariff_id,
    tariff_code,
    version,
    name,
    description,
    tariff_type_code,
    tier_strategy,
    quantity_unit,
    amount,
    currency,
    tier_brackets,
    is_active,
    metadata,
    created_at
FROM tariffs
WHERE tariff_code = $1
ORDER BY version DESC
`

type ListTariffVersionsRow struct {
	TariffID       int64       `json:"tariff_id"`
	TariffCode     string      `json:"tariff_code"`
	Version        int32       `json:"version"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	TariffTypeCode string      `json:"tariff_type_code"`
	TierStrategy   pgtype.Text `json:"tier_strategy"`
	QuantityUnit   pgtype.Text `json:"quantity_unit"`
	Amount         pgtype.Int8 `json:"amount"`
	Currency       string      `json:"currency"`
	TierBrackets   []byte      `json:"tier_brackets"`
	IsActive       bool        `json:"is_active"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) ListTariffVersions(ctx context.Context, tariffCode string) ([]ListTariffVersionsRow, error) {
	rows, err := q.db.Query(ctx, listTariffVersions, tariffCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTariffVersionsRow
	for rows.Next() {
		var i ListTariffVersionsRow
		if err := rows.Scan(
			&i.TariffID,
			&i.TariffCode,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.TariffTypeCode,
			&i.TierStrategy,
			&i.QuantityUnit,
			&i.Amount,
			&i.Currency,
			&i.TierBrackets,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
